openapi: "3.0.1"
info:
  title: "Jamf Pro API - DigiCert Trust Lifecycle Manager"
  description: "API for configuring the DigiCert Trust Lifecycle Manager settings in Jamf Pro."
  version: "1.0.0"
paths:
  /v1/pki/digicert/trust-lifecycle-manager:
    post:
      tags:
        - digicert
      summary: |
        Create DigiCert Trust Lifecycle Manager configuration with client authentication via client certificate.
      description: Create DigiCert Trust Lifecycle Manager configuration and initialize renewal monitor.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DigiCertSetting"
            examples:
              sample1:
                value:
                  caName: "Example Display Name - 1"
                  fqdn: "digicert.example.com"
                  revocationEnabled: true
                  clientCert:
                    filename: "client-cert.p12"
                    data: "MIINvwIBAzCCDXsGCSqGSIb3DQEHAaCCDWwEgg1oMIINZDCCBg8GCSqGSIb3DQEHAaCCBgAEggX8MIIF+DCCBfQGCyqGSIb3DQEMCgECoIIE/jCCBPowHAYKKoZIhvcNAQwBAzAOBAhIPjJB7Ls2fAICB9AEggTY3EKQVRtYWdwsisoMtXWIYJXvLTLm3WtBULqFdkVIXiMg0Y6cKtMdYHoLKEhyZwcsFxiUSfM4QkGpo4woshiwjFBEwc7Iu3waIGe5CVmAsZ9ynvqBirCfelmt5mLn6iU+AjR/xcYqwV2MJNO+lo8K3gVGDHvE0caJQB2blFioW7QOsGb+8GWpNNdWkbTHB6zH3XRB1lVm+9rsr1BF1l3lzEQOlc4P1nBtNumf2TVBoU6cM4lgiWA0as896nUilj1w9AAXiQcdhIT4zaaJFP4AnXqL94bDDlfceA60HNpzCYRIGOhohnxBtquUoDw6uHBnmo6PMkB2KkYNVoxk+/+egF3arCdjbj4OkWhZ/wzNGa0uHTA6nG8bNWRXULWZ/QfvQi424vKfuLSGQty1AP0VHOeoY4SkWvDz+gCEfP29C8vk4kWcnl/0dsE1wmmowuydJvL6WhGRAPii1y/BOJW0FTXav03o7SP5aYZXnr8qLKKUkmSziV1toY7YFl7lUCKYj5j/1I+5uaGlEqbjEsQs6GwL6S9M6ggpbGSBT4fp4xH1FSXeRoWbbVKuB3+Sin8lwP4ZrSTarufWpYCnnLNfYgTFiatpbP9u9BS4PaBVZTFygyvl4Gj4QtVMtZy39tRqiN82RkG61DiTeLFI0xXGqMctQLpOHU8Rn07tBZBKWI6U5wc2nDKWr60ohQPVEglt5MEqYgPuPcoUvj2GOG536pHR6HeWiX3nszv3KCNxOog8hkvs1JKoJuByhgzeUR6ylHTBOq+jNrbTJvzWGXEK6+I5rUmViITmMksumg96kUgP2ZPYzGbaJLt0lE1zD+rI05EWroZh4GQpcwfX8PQkbadR10MXbhnPe039TwhbgtDecxgNZQd0Fs4WTZqzpZOkUpcvWxHmPm1iSCd860EvNKwJos4kAlgE2tMtPpAiNqhxOzzgMiSFdxOnTV3khJ2xTL4J8UsObbn2K6qp9EhXcUUl+0Xn7C8+T4PIYkW4G5LNkIjv/3Df7VGjaTwk0rJtFwJh8k09BPA4ETNaxC/C7JFwkW9eJYtYi/UxStMSrVj1HGmnsG036C+IYDjKeUWvNK7QV2mq+Pas5WncgRU8BwgU5D2fLffRjtnP1UnnTkHsk9wocUqIaEpylIDnmUzA6mgM/4vfibF2BHDgkLjo5w2kgSjoSsRp7z23RudESgIyax21aWtmBZvDLTCn7KXGwXPELxLoU3lvOow7G8XTwAymaV/ymn6aQDp9tEwMHL0slRc3okRtAkHvhwUWpy7wXHup/aGhciA0fpkZhU1UECxGybhjPANsBzB9gUoBo2QWmKI7pjAovDWTbqHMylEi0Xumj+FxJgrdSHm9IbkX92ShJKLoD/flGfMS9pNVaqoCSsa66lPSCNqnDEF85/rr1vDBwDHSPChZri7748VWXxNzoCnbp2wYlRTUn8DOvuMDdO5W/tWnxmHgaiOxOKgoiRsl0Rm2N9E9sse5VLkXnQG4/Ybgzdq9xsxB9RdL5pnXsvBjCc+ruH3/XW4ufEq10PvdruBSz7jFqMfXJZ0APqNcRAm6UVsLSIqYbDuaDXMIJATUzy+EGVLdUcLfcMpWWxXgtUr+mJLvWTTlHTdoF57mJoY0XiFe2lz/xsumI0CgA2z0AyUmvDGB4jANBgkrBgEEAYI3EQIxADATBgkqhkiG9w0BCRUxBgQEAQAAADBdBgkqhkiG9w0BCRQxUB5OAHQAZQAtADEANgAxADMANgAxADQANAAtADYAMQA4ADQALQA0ADYAYwAwAC0AOAA3ADIAMgAtAGEAZQBmADgAMgBkADkANABmAGUAZgBkMF0GCSsGAQQBgjcRATFQHk4ATQBpAGMAcgBvAHMAbwBmAHQAIABTAG8AZgB0AHcAYQByAGUAIABLAGUAeQAgAFMAdABvAHIAYQBnAGUAIABQAHIAbwB2AGkAZABlAHIwggdNBgkqhkiG9w0BBwGgggc+BIIHOjCCBzYwggODBgsqhkiG9w0BDAoBA6CCA3AwggNsBgoqhkiG9w0BCRYBoIIDXASCA1gwggNUMIICPKADAgECAhBQpWSN5vK+pExY7iCTjMhhMA0GCSqGSIb3DQEBCwUAMCgxJjAkBgNVBAMMHWt0bnN2bS13aW4yMDE2LmVuemlhbnRlY2guY29tMB4XDTIyMDMxNTEyMjAwM1oXDTMyMDMxNTEyMjk1OFowKDEmMCQGA1UEAwwda3Ruc3ZtLXdpbjIwMTYuZW56aWFudGVjaC5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCh2WEjlnlY37yMtBhNY/2q/Mgx7hSJMpb9sK4HY/RufB0olyVwA4sKG0+ER9wnC+brkT8CDamnzeC+x5OynZ8QaP7m0tQSLCJrfJ9EapUSgD/TZv7Y+qXnVhI5sSpKXMt0g8SCQEzvS5dsLylw6VENlhvEUSFlfjcZbrCsHQgqEahaPlxz2MG35UUkBSwarTK243wtDvSXiBhmAeWQvNDJqpUlLxKNmvAWSzjfpOdEM+iRHf3Nph2wqSSOS61XUJ55fC0UIAMjzGlEYpJrd73PJTyly5ZQGErDwgyLW/Qti65jgRLg8cMNDqBSTwQwo00SvM54EFOmrQP9nq/SrlkXAgMBAAGjejB4MA4GA1UdDwEB/wQEAwIBtjAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwKAYDVR0RBCEwH4Ida3Ruc3ZtLXdpbjIwMTYuZW56aWFudGVjaC5jb20wHQYDVR0OBBYEFD6G+I03qqd9Rd1UCSMy8WxzthG7MA0GCSqGSIb3DQEBCwUAA4IBAQBN5NrClbxY4AdOVSbD319s9ApGwzhA7VH2r73Qi07UtQslLUWHjN6D78ZU/rlqYRsF4yOI3Zxcp7KV9rfOVigJPNUPU9wQe0aPnPUy4qEGd0HJpXmmj8t17l/+gtV6I0Vs0de+OY1PkjfcvFLMOfjAzbG2VxPCm0kL1Jd86b60t/iiaE2l0fxn7UfVetpRZLNZV1X9fwB+raUqN2ILhsS7bFwj3PDpzMw/9qLj/hiE6+9QksSpDhkIJDjU48GiGtkidRoATK+paO0xso3nPLNi5s+CY5NprFeqizymTzOX8DJcjtINTU2CL41k7G0r/stv1YgBQDB7Rwg6bxyTfN68MQAwggOrBgsqhkiG9w0BDAoBA6CCA4MwggN/BgoqhkiG9w0BCRYBoIIDbwSCA2swggNnMIICT6ADAgECAhAaVZcv8KdtjUbjDGvLd3toMA0GCSqGSIb3DQEBCwUAMCgxJjAkBgNVBAMMHWt0bnN2bS13aW4yMDE2LmVuemlhbnRlY2guY29tMB4XDTIyMDMxNTEyMjAwM1oXDTMyMDMxNTEyMzAwM1owIDEeMBwGA1UEAwwVaDY4aGNnLnF1aWNrLmphbWYubmV0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvBD1C4tR8vWZeSDdQ6AhynzMB47plvkqrXnmhcavlsDnu8Zfanr6gjUND0NK2Ufm0BBhH86kIcYMwehLYVNNfC3RTCT+QLo3wIn7VxUnsAPTqD23QjNwYnDTBQDkBrQIrFYaPc0RxO0MYexg/EqgEiAF1nJAZ3tndev1LBSEO5iN+8patoyV7jE3JlgF9qN0T0XCELrRpEi/pxKaVpAupXp38NBWVAJ6yqWuTCP2gcvnvo8KHHUTpJhwUcxr1aKUjX0LBnJ/mStQ8Cfckr7sLaHXyt4ei5uiQID69d/6JNoqpfoWW0EcHW8V3fiLX5fzsMBGjmRa/R8//zVM/ebpSwIDAQABo4GUMIGRMA4GA1UdDwEB/wQEAwIEsDAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwIAYDVR0RBBkwF4IVaDY4aGNnLnF1aWNrLmphbWYubmV0MB8GA1UdIwQYMBaAFD6G+I03qqd9Rd1UCSMy8WxzthG7MB0GA1UdDgQWBBT1Gk6lWWBdrF1z7n/FMgxT5Hb5YjANBgkqhkiG9w0BAQsFAAOCAQEAj0UtZ118booksRr7kDg47IhlhSlkhZVnZfkRUHY2QSYBkHNyilcb9rWJIAzrSI5q+RV+FDXDEc0at9CmH2yIb+dYSojxj1ebSCloZb5QiHfAZTFN5+AicESWb0PMGiiz1HeU8Bm2bjHIRx4OLKSm4agMck/6iBDJhduiidrEZkmz8MRFr04GE/9MAg3JG149JeCSS54seKx7tBx+dJjzHJg2HeqZtOKjaKLOnstquEVhwgGXIqH51lQd5SOfYJH1cQyi6xe7SBZ5YYYF1iubhMUqvYnbugskm35nYWk9XObw4QRnfTQNIuW6p1cz2Nk+yaDheraycaxbBGYaXMgIJzEVMBMGCSqGSIb3DQEJFTEGBAQBAAAAMDswHzAHBgUrDgMCGgQUA/Hryi7gjlbKpKpGVlTvAnjevyAEFFhGKjlcFPkz5+bUOnz1OcWq/3zPAgIH0A=="
                    password: "password-example"
        required: true
      responses:
        201:
          description: "Created"
          content:
            '*/*':
              schema:
                $ref: "DefinitionsLibrary.yaml#/components/schemas/HrefResponse"
      x-required-privileges:
        - Create DigiCert Settings
  /v1/pki/digicert/trust-lifecycle-manager/{id}:
    get:
      tags:
        - digicert
      summary: Retrieve DigiCert Trust Lifecycle Manager configuration
      description: |
        Retrieve the current configuration of the DigiCert Trust Lifecycle
        Manager.
      parameters:
        - name: id
          in: path
          description: ID of the DigiCert Trust Lifecycle Manager configuration
          required: true
          schema:
            type: string
      responses:
        200:
          description: |
            Successful response returns a DigiCert Trust Lifecycle Manager
            configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DigiCertSettingResponse'
        404:
          description: DigiCert Trust Lifecycle Manager configuration not found
          content:
            application/json:
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
      x-required-privileges:
        - Read DigiCert Settings
    patch:
      tags:
        - digicert
      summary: |
        Update DigiCert Trust Lifecycle Manager configuration
      description: Update DigiCert Trust Lifecycle Manager configuration, where the client certificate information must be provided in full or not at all.
      parameters:
        - name: "id"
          in: "path"
          description: ID of the DigiCert Trust Lifecycle Manager configuration.
          required: true
          schema:
            type: "string"
      requestBody:
        content:
          'application/merge-patch+json':
            schema:
              $ref: '#/components/schemas/DigiCertSetting'
        required: true
      responses:
        204:
          description: "No Content"
        400:
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
      x-required-privileges:
        - Update DigiCert Settings
    delete:
      tags:
        - digicert
      summary: Delete DigiCert Trust Lifecycle Manager configuration
      description: |
        Delete the current configuration of the DigiCert Trust Lifecycle
        Manager.
      parameters:
        - name: id
          in: path
          description: ID of the DigiCert Trust Lifecycle Manager configuration
          required: true
          schema:
            type: string
      responses:
        204:
          description: |
            Successful deletion of the DigiCert Trust Lifecycle Manager
            configuration
        404:
          description: Not Found
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
        409:
          description: Conflict
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
      x-required-privileges:
        - Delete DigiCert Settings
  /v1/pki/digicert/trust-lifecycle-manager/validate-client-certificate:
    post:
      tags:
        - digicert
      summary: |
        Validate DigiCert Trust Lifecycle Manager client certificate
      description: Validate DigiCert Trust Lifecycle Manager client certificate for file format and correct password. Must be base64-encoded PKCS#12 file content, obtainable by `openssl base64 < /file/path/filename.p12 | tr -d '\n' | pbcopy` in linux terminal, or similar parsing methods.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Certificate"
            examples:
              sample1:
                value:
                  filename: "client-cert.p12"
                  data: "MIINvwIBAzCCDXsGCSqGSIb3DQEHAaCCDWwEgg1oMIINZDCCBg8GCSqGSIb3DQEHAaCCBgAEggX8MIIF+DCCBfQGCyqGSIb3DQEMCgECoIIE/jCCBPowHAYKKoZIhvcNAQwBAzAOBAhIPjJB7Ls2fAICB9AEggTY3EKQVRtYWdwsisoMtXWIYJXvLTLm3WtBULqFdkVIXiMg0Y6cKtMdYHoLKEhyZwcsFxiUSfM4QkGpo4woshiwjFBEwc7Iu3waIGe5CVmAsZ9ynvqBirCfelmt5mLn6iU+AjR/xcYqwV2MJNO+lo8K3gVGDHvE0caJQB2blFioW7QOsGb+8GWpNNdWkbTHB6zH3XRB1lVm+9rsr1BF1l3lzEQOlc4P1nBtNumf2TVBoU6cM4lgiWA0as896nUilj1w9AAXiQcdhIT4zaaJFP4AnXqL94bDDlfceA60HNpzCYRIGOhohnxBtquUoDw6uHBnmo6PMkB2KkYNVoxk+/+egF3arCdjbj4OkWhZ/wzNGa0uHTA6nG8bNWRXULWZ/QfvQi424vKfuLSGQty1AP0VHOeoY4SkWvDz+gCEfP29C8vk4kWcnl/0dsE1wmmowuydJvL6WhGRAPii1y/BOJW0FTXav03o7SP5aYZXnr8qLKKUkmSziV1toY7YFl7lUCKYj5j/1I+5uaGlEqbjEsQs6GwL6S9M6ggpbGSBT4fp4xH1FSXeRoWbbVKuB3+Sin8lwP4ZrSTarufWpYCnnLNfYgTFiatpbP9u9BS4PaBVZTFygyvl4Gj4QtVMtZy39tRqiN82RkG61DiTeLFI0xXGqMctQLpOHU8Rn07tBZBKWI6U5wc2nDKWr60ohQPVEglt5MEqYgPuPcoUvj2GOG536pHR6HeWiX3nszv3KCNxOog8hkvs1JKoJuByhgzeUR6ylHTBOq+jNrbTJvzWGXEK6+I5rUmViITmMksumg96kUgP2ZPYzGbaJLt0lE1zD+rI05EWroZh4GQpcwfX8PQkbadR10MXbhnPe039TwhbgtDecxgNZQd0Fs4WTZqzpZOkUpcvWxHmPm1iSCd860EvNKwJos4kAlgE2tMtPpAiNqhxOzzgMiSFdxOnTV3khJ2xTL4J8UsObbn2K6qp9EhXcUUl+0Xn7C8+T4PIYkW4G5LNkIjv/3Df7VGjaTwk0rJtFwJh8k09BPA4ETNaxC/C7JFwkW9eJYtYi/UxStMSrVj1HGmnsG036C+IYDjKeUWvNK7QV2mq+Pas5WncgRU8BwgU5D2fLffRjtnP1UnnTkHsk9wocUqIaEpylIDnmUzA6mgM/4vfibF2BHDgkLjo5w2kgSjoSsRp7z23RudESgIyax21aWtmBZvDLTCn7KXGwXPELxLoU3lvOow7G8XTwAymaV/ymn6aQDp9tEwMHL0slRc3okRtAkHvhwUWpy7wXHup/aGhciA0fpkZhU1UECxGybhjPANsBzB9gUoBo2QWmKI7pjAovDWTbqHMylEi0Xumj+FxJgrdSHm9IbkX92ShJKLoD/flGfMS9pNVaqoCSsa66lPSCNqnDEF85/rr1vDBwDHSPChZri7748VWXxNzoCnbp2wYlRTUn8DOvuMDdO5W/tWnxmHgaiOxOKgoiRsl0Rm2N9E9sse5VLkXnQG4/Ybgzdq9xsxB9RdL5pnXsvBjCc+ruH3/XW4ufEq10PvdruBSz7jFqMfXJZ0APqNcRAm6UVsLSIqYbDuaDXMIJATUzy+EGVLdUcLfcMpWWxXgtUr+mJLvWTTlHTdoF57mJoY0XiFe2lz/xsumI0CgA2z0AyUmvDGB4jANBgkrBgEEAYI3EQIxADATBgkqhkiG9w0BCRUxBgQEAQAAADBdBgkqhkiG9w0BCRQxUB5OAHQAZQAtADEANgAxADMANgAxADQANAAtADYAMQA4ADQALQA0ADYAYwAwAC0AOAA3ADIAMgAtAGEAZQBmADgAMgBkADkANABmAGUAZgBkMF0GCSsGAQQBgjcRATFQHk4ATQBpAGMAcgBvAHMAbwBmAHQAIABTAG8AZgB0AHcAYQByAGUAIABLAGUAeQAgAFMAdABvAHIAYQBnAGUAIABQAHIAbwB2AGkAZABlAHIwggdNBgkqhkiG9w0BBwGgggc+BIIHOjCCBzYwggODBgsqhkiG9w0BDAoBA6CCA3AwggNsBgoqhkiG9w0BCRYBoIIDXASCA1gwggNUMIICPKADAgECAhBQpWSN5vK+pExY7iCTjMhhMA0GCSqGSIb3DQEBCwUAMCgxJjAkBgNVBAMMHWt0bnN2bS13aW4yMDE2LmVuemlhbnRlY2guY29tMB4XDTIyMDMxNTEyMjAwM1oXDTMyMDMxNTEyMjk1OFowKDEmMCQGA1UEAwwda3Ruc3ZtLXdpbjIwMTYuZW56aWFudGVjaC5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCh2WEjlnlY37yMtBhNY/2q/Mgx7hSJMpb9sK4HY/RufB0olyVwA4sKG0+ER9wnC+brkT8CDamnzeC+x5OynZ8QaP7m0tQSLCJrfJ9EapUSgD/TZv7Y+qXnVhI5sSpKXMt0g8SCQEzvS5dsLylw6VENlhvEUSFlfjcZbrCsHQgqEahaPlxz2MG35UUkBSwarTK243wtDvSXiBhmAeWQvNDJqpUlLxKNmvAWSzjfpOdEM+iRHf3Nph2wqSSOS61XUJ55fC0UIAMjzGlEYpJrd73PJTyly5ZQGErDwgyLW/Qti65jgRLg8cMNDqBSTwQwo00SvM54EFOmrQP9nq/SrlkXAgMBAAGjejB4MA4GA1UdDwEB/wQEAwIBtjAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwKAYDVR0RBCEwH4Ida3Ruc3ZtLXdpbjIwMTYuZW56aWFudGVjaC5jb20wHQYDVR0OBBYEFD6G+I03qqd9Rd1UCSMy8WxzthG7MA0GCSqGSIb3DQEBCwUAA4IBAQBN5NrClbxY4AdOVSbD319s9ApGwzhA7VH2r73Qi07UtQslLUWHjN6D78ZU/rlqYRsF4yOI3Zxcp7KV9rfOVigJPNUPU9wQe0aPnPUy4qEGd0HJpXmmj8t17l/+gtV6I0Vs0de+OY1PkjfcvFLMOfjAzbG2VxPCm0kL1Jd86b60t/iiaE2l0fxn7UfVetpRZLNZV1X9fwB+raUqN2ILhsS7bFwj3PDpzMw/9qLj/hiE6+9QksSpDhkIJDjU48GiGtkidRoATK+paO0xso3nPLNi5s+CY5NprFeqizymTzOX8DJcjtINTU2CL41k7G0r/stv1YgBQDB7Rwg6bxyTfN68MQAwggOrBgsqhkiG9w0BDAoBA6CCA4MwggN/BgoqhkiG9w0BCRYBoIIDbwSCA2swggNnMIICT6ADAgECAhAaVZcv8KdtjUbjDGvLd3toMA0GCSqGSIb3DQEBCwUAMCgxJjAkBgNVBAMMHWt0bnN2bS13aW4yMDE2LmVuemlhbnRlY2guY29tMB4XDTIyMDMxNTEyMjAwM1oXDTMyMDMxNTEyMzAwM1owIDEeMBwGA1UEAwwVaDY4aGNnLnF1aWNrLmphbWYubmV0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvBD1C4tR8vWZeSDdQ6AhynzMB47plvkqrXnmhcavlsDnu8Zfanr6gjUND0NK2Ufm0BBhH86kIcYMwehLYVNNfC3RTCT+QLo3wIn7VxUnsAPTqD23QjNwYnDTBQDkBrQIrFYaPc0RxO0MYexg/EqgEiAF1nJAZ3tndev1LBSEO5iN+8patoyV7jE3JlgF9qN0T0XCELrRpEi/pxKaVpAupXp38NBWVAJ6yqWuTCP2gcvnvo8KHHUTpJhwUcxr1aKUjX0LBnJ/mStQ8Cfckr7sLaHXyt4ei5uiQID69d/6JNoqpfoWW0EcHW8V3fiLX5fzsMBGjmRa/R8//zVM/ebpSwIDAQABo4GUMIGRMA4GA1UdDwEB/wQEAwIEsDAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwIAYDVR0RBBkwF4IVaDY4aGNnLnF1aWNrLmphbWYubmV0MB8GA1UdIwQYMBaAFD6G+I03qqd9Rd1UCSMy8WxzthG7MB0GA1UdDgQWBBT1Gk6lWWBdrF1z7n/FMgxT5Hb5YjANBgkqhkiG9w0BAQsFAAOCAQEAj0UtZ118booksRr7kDg47IhlhSlkhZVnZfkRUHY2QSYBkHNyilcb9rWJIAzrSI5q+RV+FDXDEc0at9CmH2yIb+dYSojxj1ebSCloZb5QiHfAZTFN5+AicESWb0PMGiiz1HeU8Bm2bjHIRx4OLKSm4agMck/6iBDJhduiidrEZkmz8MRFr04GE/9MAg3JG149JeCSS54seKx7tBx+dJjzHJg2HeqZtOKjaKLOnstquEVhwgGXIqH51lQd5SOfYJH1cQyi6xe7SBZ5YYYF1iubhMUqvYnbugskm35nYWk9XObw4QRnfTQNIuW6p1cz2Nk+yaDheraycaxbBGYaXMgIJzEVMBMGCSqGSIb3DQEJFTEGBAQBAAAAMDswHzAHBgUrDgMCGgQUA/Hryi7gjlbKpKpGVlTvAnjevyAEFFhGKjlcFPkz5+bUOnz1OcWq/3zPAgIH0A=="
                  password: "password-example"
              sample2:
                value:
                  filename: "client-cert.p12"
                  data: "MIINvwIBAzCCDXsGCSqGSIb3DQEHAaCCDWwEgg1oMIINZDCCBg8GCSqGSIb3DQEHAaCCBgAEggX8MIIF+DCCBfQGCyqGSIb3DQEMCgECoIIE/jCCBPowHAYKKoZIhvcNAQwBAzAOBAhIPjJB7Ls2fAICB9AEggTY3EKQVRtYWdwsisoMtXWIYJXvLTLm3WtBULqFdkVIXiMg0Y6cKtMdYHoLKEhyZwcsFxiUSfM4QkGpo4woshiwjFBEwc7Iu3waIGe5CVmAsZ9ynvqBirCfelmt5mLn6iU+AjR/xcYqwV2MJNO+lo8K3gVGDHvE0caJQB2blFioW7QOsGb+8GWpNNdWkbTHB6zH3XRB1lVm+9rsr1BF1l3lzEQOlc4P1nBtNumf2TVBoU6cM4lgiWA0as896nUilj1w9AAXiQcdhIT4zaaJFP4AnXqL94bDDlfceA60HNpzCYRIGOhohnxBtquUoDw6uHBnmo6PMkB2KkYNVoxk+/+egF3arCdjbj4OkWhZ/wzNGa0uHTA6nG8bNWRXULWZ/QfvQi424vKfuLSGQty1AP0VHOeoY4SkWvDz+gCEfP29C8vk4kWcnl/0dsE1wmmowuydJvL6WhGRAPii1y/BOJW0FTXav03o7SP5aYZXnr8qLKKUkmSziV1toY7YFl7lUCKYj5j/1I+5uaGlEqbjEsQs6GwL6S9M6ggpbGSBT4fp4xH1FSXeRoWbbVKuB3+Sin8lwP4ZrSTarufWpYCnnLNfYgTFiatpbP9u9BS4PaBVZTFygyvl4Gj4QtVMtZy39tRqiN82RkG61DiTeLFI0xXGqMctQLpOHU8Rn07tBZBKWI6U5wc2nDKWr60ohQPVEglt5MEqYgPuPcoUvj2GOG536pHR6HeWiX3nszv3KCNxOog8hkvs1JKoJuByhgzeUR6ylHTBOq+jNrbTJvzWGXEK6+I5rUmViITmMksumg96kUgP2ZPYzGbaJLt0lE1zD+rI05EWroZh4GQpcwfX8PQkbadR10MXbhnPe039TwhbgtDecxgNZQd0Fs4WTZqzpZOkUpcvWxHmPm1iSCd860EvNKwJos4kAlgE2tMtPpAiNqhxOzzgMiSFdxOnTV3khJ2xTL4J8UsObbn2K6qp9EhXcUUl+0Xn7C8+T4PIYkW4G5LNkIjv/3Df7VGjaTwk0rJtFwJh8k09BPA4ETNaxC/C7JFwkW9eJYtYi/UxStMSrVj1HGmnsG036C+IYDjKeUWvNK7QV2mq+Pas5WncgRU8BwgU5D2fLffRjtnP1UnnTkHsk9wocUqIaEpylIDnmUzA6mgM/4vfibF2BHDgkLjo5w2kgSjoSsRp7z23RudESgIyax21aWtmBZvDLTCn7KXGwXPELxLoU3lvOow7G8XTwAymaV/ymn6aQDp9tEwMHL0slRc3okRtAkHvhwUWpy7wXHup/aGhciA0fpkZhU1UECxGybhjPANsBzB9gUoBo2QWmKI7pjAovDWTbqHMylEi0Xumj+FxJgrdSHm9IbkX92ShJKLoD/flGfMS9pNVaqoCSsa66lPSCNqnDEF85/rr1vDBwDHSPChZri7748VWXxNzoCnbp2wYlRTUn8DOvuMDdO5W/tWnxmHgaiOxOKgoiRsl0Rm2N9E9sse5VLkXnQG4/Ybgzdq9xsxB9RdL5pnXsvBjCc+ruH3/XW4ufEq10PvdruBSz7jFqMfXJZ0APqNcRAm6UVsLSIqYbDuaDXMIJATUzy+EGVLdUcLfcMpWWxXgtUr+mJLvWTTlHTdoF57mJoY0XiFe2lz/xsumI0CgA2z0AyUmvDGB4jANBgkrBgEEAYI3EQIxADATBgkqhkiG9w0BCRUxBgQEAQAAADBdBgkqhkiG9w0BCRQxUB5OAHQAZQAtADEANgAxADMANgAxADQANAAtADYAMQA4ADQALQA0ADYAYwAwAC0AOAA3ADIAMgAtAGEAZQBmADgAMgBkADkANABmAGUAZgBkMF0GCSsGAQQBgjcRATFQHk4ATQBpAGMAcgBvAHMAbwBmAHQAIABTAG8AZgB0AHcAYQByAGUAIABLAGUAeQAgAFMAdABvAHIAYQBnAGUAIABQAHIAbwB2AGkAZABlAHIwggdNBgkqhkiG9w0BBwGgggc+BIIHOjCCBzYwggODBgsqhkiG9w0BDAoBA6CCA3AwggNsBgoqhkiG9w0BCRYBoIIDXASCA1gwggNUMIICPKADAgECAhBQpWSN5vK+pExY7iCTjMhhMA0GCSqGSIb3DQEBCwUAMCgxJjAkBgNVBAMMHWt0bnN2bS13aW4yMDE2LmVuemlhbnRlY2guY29tMB4XDTIyMDMxNTEyMjAwM1oXDTMyMDMxNTEyMjk1OFowKDEmMCQGA1UEAwwda3Ruc3ZtLXdpbjIwMTYuZW56aWFudGVjaC5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCh2WEjlnlY37yMtBhNY/2q/Mgx7hSJMpb9sK4HY/RufB0olyVwA4sKG0+ER9wnC+brkT8CDamnzeC+x5OynZ8QaP7m0tQSLCJrfJ9EapUSgD/TZv7Y+qXnVhI5sSpKXMt0g8SCQEzvS5dsLylw6VENlhvEUSFlfjcZbrCsHQgqEahaPlxz2MG35UUkBSwarTK243wtDvSXiBhmAeWQvNDJqpUlLxKNmvAWSzjfpOdEM+iRHf3Nph2wqSSOS61XUJ55fC0UIAMjzGlEYpJrd73PJTyly5ZQGErDwgyLW/Qti65jgRLg8cMNDqBSTwQwo00SvM54EFOmrQP9nq/SrlkXAgMBAAGjejB4MA4GA1UdDwEB/wQEAwIBtjAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwKAYDVR0RBCEwH4Ida3Ruc3ZtLXdpbjIwMTYuZW56aWFudGVjaC5jb20wHQYDVR0OBBYEFD6G+I03qqd9Rd1UCSMy8WxzthG7MA0GCSqGSIb3DQEBCwUAA4IBAQBN5NrClbxY4AdOVSbD319s9ApGwzhA7VH2r73Qi07UtQslLUWHjN6D78ZU/rlqYRsF4yOI3Zxcp7KV9rfOVigJPNUPU9wQe0aPnPUy4qEGd0HJpXmmj8t17l/+gtV6I0Vs0de+OY1PkjfcvFLMOfjAzbG2VxPCm0kL1Jd86b60t/iiaE2l0fxn7UfVetpRZLNZV1X9fwB+raUqN2ILhsS7bFwj3PDpzMw/9qLj/hiE6+9QksSpDhkIJDjU48GiGtkidRoATK+paO0xso3nPLNi5s+CY5NprFeqizymTzOX8DJcjtINTU2CL41k7G0r/stv1YgBQDB7Rwg6bxyTfN68MQAwggOrBgsqhkiG9w0BDAoBA6CCA4MwggN/BgoqhkiG9w0BCRYBoIIDbwSCA2swggNnMIICT6ADAgECAhAaVZcv8KdtjUbjDGvLd3toMA0GCSqGSIb3DQEBCwUAMCgxJjAkBgNVBAMMHWt0bnN2bS13aW4yMDE2LmVuemlhbnRlY2guY29tMB4XDTIyMDMxNTEyMjAwM1oXDTMyMDMxNTEyMzAwM1owIDEeMBwGA1UEAwwVaDY4aGNnLnF1aWNrLmphbWYubmV0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvBD1C4tR8vWZeSDdQ6AhynzMB47plvkqrXnmhcavlsDnu8Zfanr6gjUND0NK2Ufm0BBhH86kIcYMwehLYVNNfC3RTCT+QLo3wIn7VxUnsAPTqD23QjNwYnDTBQDkBrQIrFYaPc0RxO0MYexg/EqgEiAF1nJAZ3tndev1LBSEO5iN+8patoyV7jE3JlgF9qN0T0XCELrRpEi/pxKaVpAupXp38NBWVAJ6yqWuTCP2gcvnvo8KHHUTpJhwUcxr1aKUjX0LBnJ/mStQ8Cfckr7sLaHXyt4ei5uiQID69d/6JNoqpfoWW0EcHW8V3fiLX5fzsMBGjmRa/R8//zVM/ebpSwIDAQABo4GUMIGRMA4GA1UdDwEB/wQEAwIEsDAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwIAYDVR0RBBkwF4IVaDY4aGNnLnF1aWNrLmphbWYubmV0MB8GA1UdIwQYMBaAFD6G+I03qqd9Rd1UCSMy8WxzthG7MB0GA1UdDgQWBBT1Gk6lWWBdrF1z7n/FMgxT5Hb5YjANBgkqhkiG9w0BAQsFAAOCAQEAj0UtZ118booksRr7kDg47IhlhSlkhZVnZfkRUHY2QSYBkHNyilcb9rWJIAzrSI5q+RV+FDXDEc0at9CmH2yIb+dYSojxj1ebSCloZb5QiHfAZTFN5+AicESWb0PMGiiz1HeU8Bm2bjHIRx4OLKSm4agMck/6iBDJhduiidrEZkmz8MRFr04GE/9MAg3JG149JeCSS54seKx7tBx+dJjzHJg2HeqZtOKjaKLOnstquEVhwgGXIqH51lQd5SOfYJH1cQyi6xe7SBZ5YYYF1iubhMUqvYnbugskm35nYWk9XObw4QRnfTQNIuW6p1cz2Nk+yaDheraycaxbBGYaXMgIJzEVMBMGCSqGSIb3DQEJFTEGBAQBAAAAMDswHzAHBgUrDgMCGgQUA/Hryi7gjlbKpKpGVlTvAnjevyAEFFhGKjlcFPkz5+bUOnz1OcWq/3zPAgIH0A=="
                  password: "password-example"
      responses:
        204:
          description: DigiCert Trust Lifecycle Manager certificate for client server is of valid file format and has correct password.
      x-required-privileges:
        - Create DigiCert Settings
        - Update DigiCert Settings
      x-action: true
  /v1/pki/digicert/trust-lifecycle-manager/{id}/connection-status:
    get:
      tags:
        - digicert
      summary: Get connection status of DigiCert Trust Lifecycle Manager for a given ID
      description: Get connection status of DigiCert Trust Lifecycle Manager for a given ID.
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the DigiCert Trust Lifecycle Manager settings.
          schema:
            type: string
            example: "12"
      responses:
        200:
          description: Successful connection to DigiCert Trust Lifecycle Manager.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DigicertConnectionStatus'
        404:
          description: DigiCert Trust Lifecycle Manager settings not found.
      x-required-privileges:
        - Read DigiCert Settings
  /v1/pki/digicert/trust-lifecycle-manager/{id}/dependencies:
    get:
      tags:
        - digicert
      summary: Retrieve list of DigiCert Trust Lifecycle Manager Settings dependencies
      description: Retrieve list of DigiCert Trust Lifecycle Manager Settings dependencies.
      x-required-privileges:
        - Read DigiCert Settings
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the DigiCert Trust Lifecycle Manager configuration.
          schema:
            type: string
      responses:
        200:
          description: Success
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/DigicertDependencies'
components:
  schemas:
    Certificate:
      type: "object"
      required:
        - filename
        - data
      properties:
        filename:
          type: "string"
          description: "Client certificate filename should extend .p12."
          minLength: 1
          maxLength: 255
          example: "example.p12"
        data:
          description: Must be base-64 encoded data obtainable by `openssl base64 < /file/path/filename.p12 | tr -d '\n' | pbcopy` in linux terminal, or similar parsing methods.
          type: "array"
          items:
            type: "string"
            format: "byte"
          example: "MIINvwIBAzCCDXsGSGDqGSIb3DQEHAaCCDWwEgg1oMIINZDCCBg8GCSqGSIb3DQEHAaCCBgAEggX8MIIF+DCCBfQGCyqGSIb3DQEMCgECoIIE/jCCBPowHAYKKoZIhvcNAQwBAzAOBAhIPjJB7Ls2fAICB9AEggTY3EKQVRtYWdwsisoMtXWIYJXvLTLm3WtBULqFdkVIXiMg0Y6cKtMdYHoLKEhyZwcsFxiUSfM4QkGpo4woshiwjFBEwc7Iu3waIGe5CVmAsZ9ynvqBirCfelmt5mLn6iU+AjR/xcYqwV2MJNO+lo8K3gVGDHvE0caJQB2blFioW7QOsGb+8GWpNNdWkbTHB6zH3XRB1lVm+9rsr1BF1l3lzEQOlc4P1nBtNumf2TVBoU6cM4lgiWA0as896nUilj1w9AAXiQcdhIT4zaaJFP4AnXqL94bDDlfceA60HNpzCYRIGOhohnxBtquUoDw6uHBnmo6PMkB2KkYNVoxk+/+egF3arCdjbj4OkWhZ/wzNGa0uHTA6nG8bNWRXULWZ/QfvQi424vKfuLSGQty1AP0VHOeoY4SkWvDz+gCEfP29C8vk4kWcnl/0dsE1wmmowuydJvL6WhGRAPii1y/BOJW0FTXav03o7SP5aYZXnr8qLKKUkmSziV1toY7YFl7lUCKYj5j/1I+5uaGlEqbjEsQs6GwL6S9M6ggpbGSBT4fp4xH1FSXeRoWbbVKuB3+Sin8lwP4ZrSTarufWpYCnnLNfYgTFiatpbP9u9BS4PaBVZTFygyvl4Gj4QtVMtZy39tRqiN82RkG61DiTeLFI0xXGqMctQLpOHU8Rn07tBZBKWI6U5wc2nDKWr60ohQPVEglt5MEqYgPuPcoUvj2GOG536pHR6HeWiX3nszv3KCNxOog8hkvs1JKoJuByhgzeUR6ylHTBOq+jNrbTJvzWGXEK6+I5rUmViITmMksumg96kUgP2ZPYzGbaJLt0lE1zD+rI05EWroZh4GQpcwfX8PQkbadR10MXbhnPe039TwhbgtDecxgNZQd0Fs4WTZqzpZOkUpcvWxHmPm1iSCd860EvNKwJos4kAlgE2tMtPpAiNqhxOzzgMiSFdxOnTV3khJ2xTL4J8UsObbn2K6qp9EhXcUUl+0Xn7C8+T4PIYkW4G5LNkIjv/3Df7VGjaTwk0rJtFwJh8k09BPA4ETNaxC/C7JFwkW9eJYtYi/UxStMSrVj1HGmnsG036C+IYDjKeUWvNK7QV2mq+Pas5WncgRU8BwgU5D2fLffRjtnP1UnnTkHsk9wocUqIaEpylIDnmUzA6mgM/4vfibF2BHDgkLjo5w2kgSjoSsRp7z23RudESgIyax21aWtmBZvDLTCn7KXGwXPELxLoU3lvOow7G8XTwAymaV/ymn6aQDp9tEwMHL0slRc3okRtAkHvhwUWpy7wXHup/aGhciA0fpkZhU1UECxGybhjPANsBzB9gUoBo2QWmKI7pjAovDWTbqHMylEi0Xumj+FxJgrdSHm9IbkX92ShJKLoD/flGfMS9pNVaqoCSsa66lPSCNqnDEF85/rr1vDBwDHSPChZri7748VWXxNzoCnbp2wYlRTUn8DOvuMDdO5W/tWnxmHgaiOxOKgoiRsl0Rm2N9E9sse5VLkXnQG4/Ybgzdq9xsxB9RdL5pnXsvBjCc+ruH3/XW4ufEq10PvdruBSz7jFqMfXJZ0APqNcRAm6UVsLSIqYbDuaDXMIJATUzy+EGVLdUcLfcMpWWxXgtUr+mJLvWTTlHTdoF57mJoY0XiFe2lz/xsumI0CgA2z0AyUmvDGB4jANBgkrBgEEAYI3EQIxADATBgkqhkiG9w0BCRUxBgQEAQAAADBdBgkqhkiG9w0BCRQxUB5OAHQAZQAtADEANgAxADMANgAxADQANAAtADYAMQA4ADQALQA0ADYAYwAwAC0AOAA3ADIAMgAtAGEAZQBmADgAMgBkADkANABmAGUAZgBkMF0GCSsGAQQBgjcRATFQHk4ATQBpAGMAcgBvAHMAbwBmAHQAIABTAG8AZgB0AHcAYQByAGUAIABLAGUAeQAgAFMAdABvAHIAYQBnAGUAIABQAHIAbwB2AGkAZABlAHIwggdNBgkqhkiG9w0BBwGgggc+BIIHOjCCBzYwggODBgsqhkiG9w0BDAoBA6CCA3AwggNsBgoqhkiG9w0BCRYBoIIDXASCA1gwggNUMIICPKADAgECAhBQpWSN5vK+pExY7iCTjMhhMA0GCSqGSIb3DQEBCwUAMCgxJjAkBgNVBAMMHWt0bnN2bS13aW4yMDE2LmVuemlhbnRlY2guY29tMB4XDTIyMDMxNTEyMjAwM1oXDTMyMDMxNTEyMjk1OFowKDEmMCQGA1UEAwwda3Ruc3ZtLXdpbjIwMTYuZW56aWFudGVjaC5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCh2WEjlnlY37yMtBhNY/2q/Mgx7hSJMpb9sK4HY/RufB0olyVwA4sKG0+ER9wnC+brkT8CDamnzeC+x5OynZ8QaP7m0tQSLCJrfJ9EapUSgD/TZv7Y+qXnVhI5sSpKXMt0g8SCQEzvS5dsLylw6VENlhvEUSFlfjcZbrCsHQgqEahaPlxz2MG35UUkBSwarTK243wtDvSXiBhmAeWQvNDJqpUlLxKNmvAWSzjfpOdEM+iRHf3Nph2wqSSOS61XUJ55fC0UIAMjzGlEYpJrd73PJTyly5ZQGErDwgyLW/Qti65jgRLg8cMNDqBSTwQwo00SvM54EFOmrQP9nq/SrlkXAgMBAAGjejB4MA4GA1UdDwEB/wQEAwIBtjAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwKAYDVR0RBCEwH4Ida3Ruc3ZtLXdpbjIwMTYuZW56aWFudGVjaC5jb20wHQYDVR0OBBYEFD6G+I03qqd9Rd1UCSMy8WxzthG7MA0GCSqGSIb3DQEBCwUAA4IBAQBN5NrClbxY4AdOVSbD319s9ApGwzhA7VH2r73Qi07UtQslLUWHjN6D78ZU/rlqYRsF4yOI3Zxcp7KV9rfOVigJPNUPU9wQe0aPnPUy4qEGd0HJpXmmj8t17l/+gtV6I0Vs0de+OY1PkjfcvFLMOfjAzbG2VxPCm0kL1Jd86b60t/iiaE2l0fxn7UfVetpRZLNZV1X9fwB+raUqN2ILhsS7bFwj3PDpzMw/9qLj/hiE6+9QksSpDhkIJDjU48GiGtkidRoATK+paO0xso3nPLNi5s+CY5NprFeqizymTzOX8DJcjtINTU2CL41k7G0r/stv1YgBQDB7Rwg6bxyTfN68MQAwggOrBgsqhkiG9w0BDAoBA6CCA4MwggN/BgoqhkiG9w0BCRYBoIIDbwSCA2swggNnMIICT6ADAgECAhAaVZcv8KdtjUbjDGvLd3toMA0GCSqGSIb3DQEBCwUAMCgxJjAkBgNVBAMMHWt0bnN2bS13aW4yMDE2LmVuemlhbnRlY2guY29tMB4XDTIyMDMxNTEyMjAwM1oXDTMyMDMxNTEyMzAwM1owIDEeMBwGA1UEAwwVaDY4aGNnLnF1aWNrLmphbWYubmV0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvBD1C4tR8vWZeSDdQ6AhynzMB47plvkqrXnmhcavlsDnu8Zfanr6gjUND0NK2Ufm0BBhH86kIcYMwehLYVNNfC3RTCT+QLo3wIn7VxUnsAPTqD23QjNwYnDTBQDkBrQIrFYaPc0RxO0MYexg/EqgEiAF1nJAZ3tndev1LBSEO5iN+8patoyV7jE3JlgF9qN0T0XCELrRpEi/pxKaVpAupXp38NBWVAJ6yqWuTCP2gcvnvo8KHHUTpJhwUcxr1aKUjX0LBnJ/mStQ8Cfckr7sLaHXyt4ei5uiQID69d/6JNoqpfoWW0EcHW8V3fiLX5fzsMBGjmRa/R8//zVM/ebpSwIDAQABo4GUMIGRMA4GA1UdDwEB/wQEAwIEsDAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwIAYDVR0RBBkwF4IVaDY4aGNnLnF1aWNrLmphbWYubmV0MB8GA1UdIwQYMBaAFD6G+I03qqd9Rd1UCSMy8WxzthG7MB0GA1UdDgQWBBT1Gk6lWWBdrF1z7n/FMgxT5Hb5YjANBgkqhkiG9w0BAQsFAAOCAQEAj0UtZ118booksRr7kDg47IhlhSlkhZVnZfkRUHY2QSYBkHNyilcb9rWJIAzrSI5q+RV+FDXDEc0at9CmH2yIb+dYSojxj1ebSCloZb5QiHfAZTFN5+AicESWb0PMGiiz1HeU8Bm2bjHIRx4OLKSm4agMck/6iBDJhduiidrEZkmz8MRFr04GE/9MAg3JG149JeCSS54seKx7tBx+dJjzHJg2HeqZtOKjaKLOnstquEVhwgGXIqH51lQd5SOfYJH1cQyi6xe7SBZ5YYYF1iubhMUqvYnbugskm35nYWk9XObw4QRnfTQNIuW6p1cz2Nk+yaDheraycaxbBGYaXMgIJzEVMBMGCSqGSIb3DQEJFTEGBAQBAAAAMDswHzAHBgUrDgMCGgQUA/Hryi7gjlbKpKpGVlTvAnjevyAEFFhGKjlcFPkz5+bUOnz1OcWq/3zPAgIH0A=="
        password:
          writeOnly: true
          nullable: true
          minLength: 1
          maxLength: 255
          type: "string"
          format: password
          example: "password-example"
    DigiCertSetting:
      type: "object"
      description: "DigiCert Trust Lifecycle Manager object to create, or update with a merge-patch strategy. Certificate data must be provided in full, or not at all for update with merge-patch strategy."
      properties:
        caName:
          type: "string"
          minLength: 1
          maxLength: 255
          example: "Example Display Name"
        fqdn:
          type: "string"
          minLength: 1
          maxLength: 255
          example: "digicert.example.com"
        revocationEnabled:
          type: "boolean"
          example: true
        clientCert:
          $ref: "#/components/schemas/Certificate"
    DigiCertSettingResponse:
      type: "object"
      description: "DigiCert Trust Lifecycle Manager response object."
      properties:
        id:
          type: "string"
          readOnly: true
          example: "1"
        caName:
          type: "string"
          minLength: 1
          maxLength: 255
          example: "Example Display Name"
        fqdn:
          type: "string"
          minLength: 1
          maxLength: 255
          example: "digicert.example.com"
        revocationEnabled:
          type: "boolean"
          example: true
        clientCert:
          $ref: "#/components/schemas/CertificateResponse"
    CertificateResponse:
      type: "object"
      properties:
        filename:
          type: "string"
          description: "Client certificate filename with .p12 extension."
          readOnly: true
          maxLength: 255
          example: "example.p12"
        serialNumber:
          type: "string"
          readOnly: true
          example: "123456789456123"
        subject:
          type: "string"
          readOnly: true
          example: "CN=SubjectName, OU=OrganizationalUnit, O=Organization, L=Location, ST=State, C=Country"
        issuer:
          type: "string"
          readOnly: true
          example: "IssuerName"
        expirationDate:
          type: "string"
          readOnly: true
          format: date-time
          example: 2018-10-15T16:39:56Z
    DigicertConnectionStatus:
      type: "object"
      properties:
        status:
          type: "string"
          readOnly: true
          example: "Successfully connected"
          minLength: 1
          maxLength: 255
    DigicertDependencies:
      type: object
      properties:
        totalCount:
          type: integer
          example: 1
          nullable: false
        results:
          type: array
          items:
            $ref: '#/components/schemas/DigicertDependency'
    DigicertDependency:
      type: object
      properties:
        configProfileId:
          type: integer
          example: 1
          nullable: false
        configProfileName:
          type: string
          example: 'name'
        configProfileType:
          type: string
          enum: [ "OSX_CONFIGURATION_PROFILE", "IOS_CONFIGURATION_PROFILE" ]
          example: "OSX_CONFIGURATION_PROFILE"
          readOnly: true
          nullable: false
